name: mymsg
description: MyMsg - Your Secure Messenger
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.3
  flutter_native_splash: ^2.3.4
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0


dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/result.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/result.png"
    background_color: "#FFFFFF"
    theme_color: "#hexcode"

flutter:
  uses-material-design: true
  assets:
    - assets/l10n/
    - assets/icons/
